### PR TITLE
agent,cli,common: feature - auto graft sync

### LINKED ISSUE #439: Automatically resolve and index grafting dependencies
When trying to index a subgraph that has a graft base, unless the base is already syncing, indexer-agent shows this error:

```
subgraph validation error: [the graft base is invalid: deployment not found: QmdSqd9g4VbWMJ22HBfLZ3CDC8DL95yWPompNeyER12cL1]"
```

graph-node:
```
Jul 20 02:38:17.898 ERRO subgraph_deploy failed, params: SubgraphDeployParams { name: SubgraphName("indexer-agent/mVwGejjBjE"), ipfs_hash: DeploymentHash("QmQ7xAxvwPhP4ZqiNZBscVuu5ZmfD9By1i3YmVwGejjBjE"), node_id: Some(NodeId("index-node-0")), debug_fork: None }, error: ManifestValidationError([GraftBaseInvalid("deployment not found: QmdSqd9g4VbWMJ22HBfLZ3CDC8DL95yWPompNeyER12cL1")]), component: JsonRpcServer
```

The agent could automatically resolve any grafting dependencies and ensure that those are indexing too. This is currently a manual process.

### PR DESCRIPTION
**Pull request by dwerner**
closes #439 

Adds behavior: when an ipfs endpoint is specified, we can crawl subgraph manifests and deploy the dependencies needed to make the graft successful.

This PR adds a new migration and ActionStatus enum variant "deploying" in order to more carefully implement re-entrance for the action execution flow.

### CODE REVIEW

File: packages/indexer-common/src/graph-node.ts [hunk 1]
```diff
@@ -625,6 +718,231 @@ export class GraphNode {
...
+            status: deployed,
+          })
+          break
+        }
+        this.logger.info(`Subgraph deployment not yet active, waiting...`, {
+          subgraph: subgraphDeployment.ipfsHash,
+          attempt,
+          deployed,
+        })
+        attempt += 1
```
Comment (fordN) [inline packages/indexer-common/src/graph-node.ts:861]: Am I reading this correctly: the loop-wait will try 5 times, with a 3 second pause in between attempts, after which it will fail out? That doesn't leave much time for the dependency to sync does it?

**Review by fordN — COMMENTED** [review]
Very nice! I just have a few logging and config questions before I approve.

File: docs/networks/arbitrum-one.md [hunk 2]
```diff
@@ -49,8 +49,8 @@ Other network contracts can be found in [graphprotocol/contracts](https://github
...
 | `INDEXER_AGENT_EPOCH_SUBGRAPH_ENDPOINT`     | `--epoch-subgraph-endpoint`     | `https://gateway-arbitrum.network.thegraph.com/api/[api-key]/subgraphs/id/4KFYqUWRTZQ9gn7GPHC6YQ2q15chJfVrX43ezYcwkgxB`   |
-| `INDEXER_AGENT_TAP_SUBGRAPH_DEPLOYMENT`     | `--tap-subgraph-deployment`     | [![Dynamic JSON Badge](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fthegraph.com%2Fexplorer%2F_next%2Fdata%2F5PBypsdmUEy39BcWLsyp0%2Fsubgraphs%2F4sukbNVTzGELnhdnpyPqsf1QqtzNHEYKKmJkgaT8z6M1.json%3Fview%3DAbout%26chain%3Darbitrum-one%26id%3D4sukbNVTzGELnhdnpyPqsf1QqtzNHEYKKmJkgaT8z6M1&query=%24.pageProps.subgraph.currentVersion.subgraphDeployment.ipfsHash&label=deployment-id)](https://thegraph.com/explorer/subgraphs/4sukbNVTzGELnhdnpyPqsf1QqtzNHEYKKmJkgaT8z6M1)   |
-| `INDEXER_AGENT_TAP_SUBGRAPH_ENDPOINT`       | `--tap-subgraph-endpoint`       | `https://gateway-arbitrum.network.thegraph.com/api/[api-key]/subgraphs/id/4sukbNVTzGELnhdnpyPqsf1QqtzNHEYKKmJkgaT8z6M1` |
+| `INDEXER_AGENT_TAP_SUBGRAPH_ENDPOINT` | `--tap-subgraph-endpoint` | `https://gateway-arbitrum.network.thegraph.com/api/[api-key]/subgraphs/id/4sukbNVTzGELnhdnpyPqsf1QqtzNHEYKKmJkgaT8z6M1` |
```
[the remark this answers is not in the document]
Comment (dwerner) [reply docs/networks/arbitrum-one.md:52]: Yeah not sure why this was removed.

File: packages/indexer-common/src/graph-node.ts (hunk 1 above)
Comment (dwerner) [reply packages/indexer-common/src/graph-node.ts:861]: This does what you're saying but only until graph-node reports the deployment as active, not finished syncing. If after that time has passed and graph-node still isn't showing the deployment is active, then we end things.

**Review by fordN — APPROVED** [review]
LGTM 👍
