### PR TITLE
fix: use subgraph timestamp for tap

### LINKED ISSUE #993: Pending RAVs doesn't take into account sender_address
Pending RAVs filters only uses `allocationID`s to filter and decide how to update on the database, but ravs are unique given a tuple (sender, allocation) so we need to update it to not have problems with multiple senders.

### LINKED ISSUE #994: RAVs retry is breaking if subgraph is late
The current code expect that subgraph is up to date at all moments. This is breaking on the following scenario:

1. RAV is redeemed and marked as redeemed.
2. Subgraph is late, so it doesn't return the rav transaction
3. Retry system thinks that it was a reorg and remove the "redeemed flag"
4. System retries it but it fails with "rav already redeemed"

We must fix this issue and indexers that already have a rav on this state should be able to recover itself by:
- If the RAV transaction already exists, update the rav's "redeemed flag".

### PR DESCRIPTION
**Pull request by gusinacio**
Fixes #993
Fixes #994

### CODE REVIEW

**Review by carlosvdr — APPROVED** [review]
sheesh nice, LGTM

File: packages/indexer-common/src/allocations/query-fees.ts [hunk 1]
```diff
@@ -690,7 +690,11 @@ export class AllocationReceiptCollector implements ReceiptCollector {
         ),
       },
     )
-    return response.data!
+    if (!response.data) {
```
Comment (carlosvdr) [inline packages/indexer-common/src/allocations/query-fees.ts:693]: This was added in case an undefined or None is returned?
Cause it can return an empty response

File: packages/indexer-common/src/allocations/__tests__/tap.test.ts [hunk 2]
```diff
@@ -125,25 +151,209 @@ describe('TAP', () => {
     timeout,
   )
 
+  test('should revert the rav request', async () => {
```
Comment (aasseman) [inline packages/indexer-common/src/allocations/__tests__/tap.test.ts:154]: Would that be more accurate?
```suggestion
  test('`revertRavsRedeemed` should revert RAV redeem status in DB only if older than subgraph last block', async () => {
```

File: packages/indexer-common/src/allocations/__tests__/tap.test.ts [hunk 3]
```diff
@@ -125,25 +151,209 @@ describe('TAP', () => {
...
+        final: false,
+        redeemedAt: {
+          [Op.ne]: null,
+        },
+      },
+    })
+    expect(lastRedeemedRavs).toEqual([])
+  })
+
+  test('should not revert the rav request, allocation_id not in the list ', async () => {
```
Comment (aasseman) [inline packages/indexer-common/src/allocations/__tests__/tap.test.ts:237]:
```suggestion
  test('`revertRavsRedeemed` should not revert the RAV redeem status in DB if (allocation, sender) not in the revert list ', async () => {
```

File: packages/indexer-common/src/allocations/__tests__/tap.test.ts [hunk 4]
```diff
@@ -125,25 +151,209 @@ describe('TAP', () => {
...
+    // we have a redeemed non-final rav in our database
```
Comment (aasseman) [inline packages/indexer-common/src/allocations/__tests__/tap.test.ts:238]: Is this comment to be removed?

File: packages/indexer-common/src/allocations/__tests__/tap.test.ts [hunk 5]
```diff
@@ -245,68 +453,72 @@ describe('TAP', () => {
   )
 
   test(
-    'test mark final rav',
+    'test mark final rav via filterAndUpdateRavs',
```
Comment (aasseman) [inline packages/indexer-common/src/allocations/__tests__/tap.test.ts:456]:
```suggestion
    'test mark final rav via `filterAndUpdateRavs`',
```

**Review by aasseman — CHANGES_REQUESTED** [review]

File: packages/indexer-common/src/allocations/query-fees.ts (hunk 1 above)
Comment (gusinacio) [reply packages/indexer-common/src/allocations/query-fees.ts:693]: It should only return empty response in case there was an error. In that case, we want to throw an error.

File: packages/indexer-common/src/allocations/query-fees.ts [hunk 6]
```diff
@@ -178,9 +193,13 @@ export class AllocationReceiptCollector implements ReceiptCollector {
     // flag during startup.
     collector.startReceiptCollecting()
     collector.startVoucherProcessing()
-    if (collector.tapContracts) {
+    if (collector.tapContracts && collector.tapSubgraph) {
       collector.logger.info(`RAV processing is initiated`)
       collector.startRAVProcessing()
+    } else {
+      collector.logger.info(`RAV process not initiated. 
+        Tap Contracts: ${!!collector.tapSubgraph}.
```
[the remark this answers is not in the document]
Comment (gusinacio) [reply packages/indexer-common/src/allocations/query-fees.ts:201]: Done

File: packages/indexer-common/src/allocations/query-fees.ts [hunk 7]
```diff
@@ -564,73 +588,158 @@ export class AllocationReceiptCollector implements ReceiptCollector {
...
+    return await this.models.receiptAggregateVouchers.findAll({
       where: { last: true, final: false },
     })
-    // Obtain allocationIds to use as filter in subgraph
-    const unfinalizedRavsAllocationIds = unfinalizedRAVs.map((rav) =>
-      rav.getSignedRAV().rav.allocationId.toLowerCase(),
+  }
+
+  private async filterAndUpdateRavs(
+    ravLastNotFinal: ReceiptAggregateVoucher[],
```
[the remark this answers is not in the document]
Comment (gusinacio) [reply packages/indexer-common/src/allocations/query-fees.ts:597]: Done

File: packages/indexer-common/src/allocations/query-fees.ts [hunk 8]
```diff
@@ -564,73 +588,158 @@ export class AllocationReceiptCollector implements ReceiptCollector {
...
-      // https://github.com/sequelize/sequelize/issues/7664 (bug been open for 7 years no fix yet or ever)
+    // we use the subgraph timestamp to make decisions
+    // block timestamp minus 1 minute (because of blockchain timestamp uncertainty)
+    const ONE_MINUTE = 60
+    const blockTimestampSecs = tapSubgraphResponse._meta.block.timestamp - ONE_MINUTE
+
+    // Mark RAVs as unredeemed in DB if the TAP subgraph couldn't find the redeem Tx.
+    // To handle a chain reorg that "unredeemed" the RAVs.
+    // WE use sql directly due to a bug in sequelize update:
+    // https://github.com/sequelize/sequelize/issues/7664 (bug been open for 7 years no fix yet or ever)
```
[the remark this answers is not in the document]
Comment (gusinacio) [reply packages/indexer-common/src/allocations/query-fees.ts:642]: Thanks, done

File: packages/indexer-common/src/allocations/__tests__/tap.test.ts (hunk 2 above)
Comment (gusinacio) [reply packages/indexer-common/src/allocations/__tests__/tap.test.ts:154]: Seems more accurate indeed, updated!

File: packages/indexer-common/src/allocations/__tests__/tap.test.ts (hunk 3 above)
Comment (gusinacio) [reply packages/indexer-common/src/allocations/__tests__/tap.test.ts:237]: Done

File: packages/indexer-common/src/allocations/__tests__/tap.test.ts (hunk 4 above)
Comment (gusinacio) [reply packages/indexer-common/src/allocations/__tests__/tap.test.ts:238]: I usually create english sentenses to structure the test, and then implement the code. But this felt disconnected, gonna remove it.

File: packages/indexer-common/src/allocations/__tests__/tap.test.ts (hunk 5 above)
Comment (gusinacio) [reply packages/indexer-common/src/allocations/__tests__/tap.test.ts:456]: done

**Review by aasseman — APPROVED** [review]
LGTM. Tested in prod and it redeems RAVs fine.

**Review by dwerner — APPROVED** [review]
