### PR TITLE
indexer-agent: add max batch size, tweak claim defaults

### LINKED ISSUE #330: Allocation failed - JavaScript heap out of memory
```json
{
  "header": {
    "reportVersion": 1,
    "event": "Allocation failed - JavaScript heap out of memory",
    "trigger": "FatalError",
    "filename": "report.20211201.083237.1.0.001.json",
    "dumpEventTime": "2021-12-01T08:32:37Z",
    "dumpEventTimeStamp": "1638347557628",
    "processId": 1,
    "cwd": "/opt/indexer/packages/indexer-agent",
    "commandLine": [
      "node",
      "dist/index.js",
      "start"
    ],
    "nodejsVersion": "v12.16.0",
    "glibcVersionRuntime": "2.24",
    "glibcVersionCompiler": "2.17",
    "wordSize": 64,
    "arch": "x64",
    "platform": "linux",
    "componentVersions": {
      "node": "12.16.0",
      "v8": "7.8.279.23-node.31",
      "uv": "1.34.0",
      "zlib": "1.2.11",
      "brotli": "1.0.7",
      "ares": "1.15.0",
      "modules": "72",
      "nghttp2": "1.40.0",
      "napi": "5",
      "llhttp": "2.0.4",
      "http_parser": "2.9.3",
      "openssl": "1.1.1d",
      "cldr": "35.1",
      "icu": "64.2",
      "tz": "2019c",
      "unicode": "12.1"
    },
    "release": {
      "name": "node",
      "lts": "Erbium",
      "headersUrl": "https://nodejs.org/download/release/v12.16.0/node-v12.16.0-headers.tar.gz",
      "sourceUrl": "https://nodejs.org/download/release/v12.16.0/node-v12.16.0.tar.gz"
    },
    "osName": "Linux",
    "osRelease": "5.4.0-88-generic",
    "osVersion": "#99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021",
    "osMachine": "x86_64",
    "cpus": [
      {
        "model": "DO-Regular",
        "speed": 2294,
        "user": 113803300,
        "nice": 132000,
        "sys": 27101800,
        "idle": 10858093700,
        "irq": 0
      },
      {
        "model": "DO-Regular",
        "speed": 2294,
        "user": 116284600,
        "nice": 124100,
        "sys": 27511000,
        "idle": 10854713700,
        "irq": 0
      },
      {
        "model": "DO-Regular",
        "speed": 2294,
        "user": 115796200,
        "nice": 182200,
        "sys": 27146300,
        "idle": 10854000300,
        "irq": 0
      },
      {
        "model": "DO-Regular",
        "speed": 2294,
        "user": 112278700,
        "nice": 108500,
        "sys": 26455100,
        "idle": 10846905700,
        "irq": 0
      }
    ],
    "networkInterfaces": [
      {
        "name": "lo",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "127.0.0.1",
        "netmask": "255.0.0.0",
        "family": "IPv4"
      },
      {
        "name": "eth0",
        "internal": false,
        "mac": "02:42:ac:12:00:06",
        "address": "172.18.0.6",
        "netmask": "255.255.0.0",
        "family": "IPv4"
      }
    ],
    "host": "57f2b4dc7f49"
  },
  "javascriptStack": {
    "message": "No stack.",
    "stack": [
      "Unavailable."
    ]
  },
  "nativeStack": [
    {
      "pc": "0x0000000000bd6a75",
      "symbol": "report::TriggerNodeReport(v8::Isolate*, node::Environment*, char const*, char const*, std::string const&, v8::Local<v8::String>) [node]"
    },
    {
      "pc": "0x0000000000aa04ec",
      "symbol": "node::OnFatalError(char const*, char const*) [node]"
    },
    {
      "pc": "0x0000000000c0db6e",
      "symbol": "v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]"
    },
    {
      "pc": "0x0000000000c0dee9",
      "symbol": "v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]"
    },
    {
      "pc": "0x0000000000dba835",
      "symbol": " [node]"
    },
    {
      "pc": "0x0000000000dbaec6",
      "symbol": "v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]"
    },
    {
      "pc": "0x0000000000dc76da",
      "symbol": "v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]"
    },
    {
      "pc": "0x0000000000dc85e5",
      "symbol": "v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]"
    },
    {
      "pc": "0x0000000000dcb09c",
      "symbol": "v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]"
    },
    {
      "pc": "0x0000000000d91a8b",
      "symbol": "v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]"
    },
    {
      "pc": "0x00000000010d479e",
      "symbol": "v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]"
    },
    {
      "pc": "0x0000000001457299",
      "symbol": " [node]"
    }
  ],
  "javascriptHeap": {
    "totalMemory": 2151784448,
    "totalCommittedMemory": 2150557408,
    "usedMemory": 2115651136,
    "availableMemory": 47974096,
    "memoryLimit": 2197815296,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 262144,
        "committedMemory": 33088,
        "capacity": 32808,
        "used": 32808,
        "available": 0
      },
      "new_space": {
        "memorySize": 2097152,
        "committedMemory": 1338200,
        "capacity": 1047456,
        "used": 321088,
        "available": 726368
      },
      "old_space": {
        "memorySize": 2139504640,
        "committedMemory": 2139322152,
        "capacity": 2106591168,
        "used": 2106421744,
        "available": 169424
      },
      "code_space": {
        "memorySize": 3051520,
        "committedMemory": 2995296,
        "capacity": 2524192,
        "used": 2524192,
        "available": 0
      },
      "map_space": {
        "memorySize": 2887680,
        "committedMemory": 2887360,
        "capacity": 2466000,
        "used": 2466000,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 3358720,
        "committedMemory": 3358720,
        "capacity": 3340760,
        "used": 3340760,
        "available": 0
      },
      "code_large_object_space": {
        "memorySize": 622592,
        "committedMemory": 622592,
        "capacity": 544544,
        "used": 544544,
        "available": 0
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 1047456,
        "used": 0,
        "available": 1047456
      }
    }
  },
  "resourceUsage": {
    "userCpuSeconds": 16035.4,
    "kernelCpuSeconds": 749.41,
    "cpuConsumptionPercent": 34.1008,
    "maxRss": 5395677184,
    "pageFaults": {
      "IORequired": 22,
      "IONotRequired": 8297107
    },
    "fsActivity": {
      "reads": 2944,
      "writes": 0
    }
  },
  "uvthreadResourceUsage": {
    "userCpuSeconds": 6775.92,
    "kernelCpuSeconds": 512.181,
    "cpuConsumptionPercent": 14.8069,
    "fsActivity": {
      "reads": 2896,
      "writes": 0
    }
  },
  "libuv": [
  ],
  "environmentVariables": {
    "PATH": "/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "HOSTNAME": "57f2b4dc7f49",
    "INDEXER_AGENT_MNEMONIC": "",
    "INDEXER_AGENT_INDEXER_ADDRESS": "",
    "INDEXER_AGENT_INDEX_NODE_IDS": "index_node_0",
    "INDEXER_AGENT_INJECT_DAI": "true",
    "INDEXER_AGENT_ETHEREUM": "",
    "INDEXER_AGENT_ETHEREUM_NETWORK": "rinkeby",
    "INDEXER_AGENT_RESTAKE_REWARDS": "false",
    "INDEXER_AGENT_ALLOCATION_CLAIM_THRESHOLD": "1000",
    "INDEXER_AGENT_GRAPH_NODE_QUERY_ENDPOINT": "http://query-node:8000",
    "INDEXER_AGENT_GRAPH_NODE_STATUS_ENDPOINT": "http://index-node:8030/graphql",
    "INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT": "http://index-node:8020",
    "INDEXER_AGENT_PUBLIC_INDEXER_URL": "",
    "INDEXER_AGENT_INDEXER_GEO_COORDINATES": "-60.16952 24.93545",
    "INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT": "https://gateway.testnet.thegraph.com/network",
    "INDEXER_AGENT_NETWORK_SUBGRAPH_DEPLOYMENT": "QmYnGeUXVNZd3MupWqPwZekCriF2CVkpoXZbuSZB9t7eQS",
    "INDEXER_AGENT_POSTGRES_HOST": "postgres-agent",
    "INDEXER_AGENT_POSTGRES_USERNAME": "agent-service",
    "INDEXER_AGENT_POSTGRES_PASSWORD": "",
    "INDEXER_AGENT_POSTGRES_DATABASE": "agent-service",
    "INDEXER_AGENT_VECTOR_NODE": "http://vector-node:8000",
    "INDEXER_AGENT_VECTOR_EVENT_SERVER": "http://indexer-agent:8001",
    "INDEXER_AGENT_VECTOR_EVENT_SERVER_PORT": "10001",
    "INDEXER_AGENT_COLLECT_RECEIPTS_ENDPOINT": "https://gateway.testnet.thegraph.com/collect-receipts",
    "NODE_VERSION": "12.16.0",
    "YARN_VERSION": "1.22.0",
    "NODE_ENV": "production",
    "ETHEREUM": "",
    "HOME": "/root"
  },
  "userLimits": {
    "core_file_size_blocks": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "data_seg_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "file_size_blocks": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_locked_memory_bytes": {
      "soft": 65536,
      "hard": 65536
    },
    "max_memory_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "open_files": {
      "soft": 10000,
      "hard": 10000
    },
    "stack_size_bytes": {
      "soft": 8388608,
      "hard": "unlimited"
    },
    "cpu_time_seconds": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_user_processes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "virtual_memory_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    }
  },
  "sharedObjects": [
    "linux-vdso.so.1",
    "/lib/x86_64-linux-gnu/libdl.so.2",
    "/usr/lib/x86_64-linux-gnu/libstdc++.so.6",
    "/lib/x86_64-linux-gnu/libm.so.6",
    "/lib/x86_64-linux-gnu/libgcc_s.so.1",
    "/lib/x86_64-linux-gnu/libpthread.so.0",
    "/lib/x86_64-linux-gnu/libc.so.6",
    "/lib64/ld-linux-x86-64.so.2",
    "/opt/indexer/node_modules/bufferutil/prebuilds/linux-x64/node.napi.node",
    "/opt/indexer/node_modules/utf-8-validate/prebuilds/linux-x64/node.napi.node",
    "/opt/indexer/node_modules/@graphprotocol/cost-model/native/index.node",
    "/lib/x86_64-linux-gnu/librt.so.1",
    "/opt/indexer/node_modules/eccrypto-js/node_modules/secp256k1/build/Release/secp256k1.node",
    "/lib/x86_64-linux-gnu/libnss_files.so.2",
    "/lib/x86_64-linux-gnu/libnss_dns.so.2",
    "/lib/x86_64-linux-gnu/libresolv.so.2"
  ]
}
```

### PR DESCRIPTION
**Pull request by chriswessels**
- Updates defaults for batch rebate claiming to set the individual rebate threshold to `200` GRT, and the batch claim threshold to `2000` GRT. This should prevent claiming unprofitable rebates, and also increases claim efficiency by leveraging batching.
- This sets a maximum batch size of 100 claims, preventing constructing transactions that are larger than the block gas limit

Should fix #330

### CODE REVIEW

File: packages/indexer-agent/src/network.ts [hunk 1]
```diff
@@ -1365,11 +1369,23 @@ export class Network {
...
 
-      const allocationIds = allocations.map(allocation => allocation.id)
+      // Max claims per batch should roughly be equal to average gas per claim / block gas limit
+      // On-chain data shows an average of 120k gas per claim and the block gas limit is 15M
+      // If we add a 30k gas buffer (for 150k estimated gas per claim)
+      // Then we could fit a maximum of a 100 claim batch in a block
+      const MAX_CLAIMS_PER_BATCH = 100
+      const allocationIds = allocations
+        .map(allocation => allocation.id)
+        .slice(0, MAX_CLAIMS_PER_BATCH)
```
Comment (fordN) [inline packages/indexer-agent/src/network.ts:1379]: So talking through this: 
In the case that there are more than 100 claims in a potential batch this will limit it to 100 and discard the rest.  Those "discarded" allocations will then be processed on the next loop?

Comment (chriswessels) [reply packages/indexer-agent/src/network.ts:1379]: That's right. It's also the reason I added the second log to clarify the allocation IDs that were included in the batch.

**Review by fordN — APPROVED** [review]
Looks good!  I think it's ready to merge once the CI builds are successful.
